
spring:
  profiles: default

server:
  port: 8086

mongo:
  location: localhost

---

spring:
  profiles: compose

server:
  port: 8080

mongo:
  location: mongo

---

spring:
  profiles: production

server:
  port: 8086

mongo:
  location: mongo.internal.block16
