
spring:
  profiles: default

server:
  port: 8086

mongo:
  location: localhost

redis:
  hostname: localhost

---

spring:
  profiles: compose

server:
  port: 8080

mongo:
  location: mongo

redis:
  hostname: redis

---

spring:
  profiles: production

server:
  port: 8086

mongo:
  location: mongo.internal.block16

redis:
  hostname: redis.internal.block16
